### ISSUE TITLE
Gravity forms integration not working

### ISSUE THREAD

**Issue by tw-360vier** [mosparo/wordpress-plugin#17]
One of our clients uses mosparo for spam protection with their gravity forms and some time ago, it seems to have stopped working.
The currently uses plugin versions are:

Gravity Forms: 2.9.15
mosparo Integration: 1.14.0

With each submission, it complains about a missing validation or submit token.

And indeed, when i look at the submitted payload, the _mosparo_validationToken field is empty.
When ajax is enabled, after each submission there is also a javascript error printed to the console:

```
Uncaught ReferenceError: gform is not defined
at kontakt/:220:21
at kontakt/:232:15
```

Ajax enabled:
<img width="2554" height="1208" alt="Image" src="https://github.com/user-attachments/assets/8565dc62-ae71-4e2d-88d5-0b9c51ea28bc" />

Ajax disabled:
<img width="2558" height="1205" alt="Image" src="https://github.com/user-attachments/assets/84e6cd00-fdae-41f5-b519-a52c23120c54" />

Any help with this issue would be greatly appreciated.

**Comment by zepich** [comment]
Hi @tw-360vier 

Thank you very much for your detailed description of the issue, and I'm sorry for the trouble.

I will have a look and let you know as soon as I know more.

Kind regards,
zepich

**Comment by zepich** [comment]
Hi @tw-360vier 

We've just released v1.14.1, which contains a fix for this issue. The code that generated the problem is only needed for the form editor in the backend and is not required at all in the frontend.

Please let me know if everything works as expected with your form.

Thank you very much for reporting this issue!

Kind regards,
zepich

**Comment by tw-360vier** [comment]
Hey @zepich ,
Thank you for your quick response!
I tested the new release and the JavaScript error is gone,
but the form still complains about a missing validation or submit token.
So unfortunately, my client's problem is not solved, yet:

<img width="2271" height="1135" alt="Image" src="https://github.com/user-attachments/assets/2828eb5e-4aba-4116-9db7-f590860797e4" />

**Comment by zepich** [comment]
Hi @tw-360vier 

Perfect, thank you very much for your feedback and help! Sorry for the trouble!

Kind regards,
zepich
